### ISSUE TITLE
Installation support

### ISSUE THREAD

**Issue by magnushasselquist** [ndbroadbent/mac_airtag_to_mqtt#1]
Hi!
Hoping to get it to work on my mac.
Not 100% sure about the installation procedure:
- Downloaded/extracted all to /opt/mac_airtag_to_mqtt)
- Copied the .env.example file to .env and modified with my details (but still keeping it in /opt/mac_airtag_to_mqtt) - correct?
- Created the /Library/LaunchDaemons/com.ndbroadbent.mac_airtag_to_mqtt.plist as per instructions
- Started it as per instructions

- > Nothing happens - Where to check?

In addition: What does the key AIRPODS_NAME mean?

Best regards,
Magnus

**Comment by ndbroadbent** [comment]
Hi @magnushasselquist, sorry for the delay, this is quite tricky to set up and debug so unfortunately I can't offer too much support. "AIRPODS_NAME" is if you have a pair of AirPods, there is some code to handle a special case around naming. For example: `AIRPODS_NAME="Nathan's AirPods"`

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
Not sure if this will help or not, but I noticed that the this is the first line of mac_airtag_to_mqtt.rb:

`#!/Users/ndbroadbent/.rbenv/versions/3.1.2/bin/ruby`

I have installed ruby-3.1.2 and updated mac_airtag_to_mqtt.rb to the following:

`#!/Users/[[MyUserName]]/.rbenv/versions/3.1.2/bin/ruby`

but now receive this error when attempting to test ./mac_airtag_to_mqtt.rb:

/Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/byebug-11.1.3/lib/byebug/core.rb:4:in `require': incompatible library version - /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/byebug-11.1.3/lib/byebug/byebug.bundle (LoadError)
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/byebug-11.1.3/lib/byebug/core.rb:4:in `<top (required)>'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/byebug/processors/pry_processor.rb:3:in `require'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/byebug/processors/pry_processor.rb:3:in `<top (required)>'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug/pry_ext.rb:3:in `require'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug/pry_ext.rb:3:in `<top (required)>'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug/cli.rb:4:in `require'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug/cli.rb:4:in `<top (required)>'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug.rb:4:in `require'
	from /Users/[[MyUserName]]/.rvm/gems/ruby-3.1.2/gems/pry-byebug-3.10.1/lib/pry-byebug.rb:4:in `<top (required)>'
	from ./mac_airtag_to_mqtt.rb:14:in `require'
	from ./mac_airtag_to_mqtt.rb:14:in `<main>'

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
I solved my issue with byebug and got this working!  Since pry-byebug's use is for debugging and it was already broken, I decided to comment out the require byebug line in mac_airtag_to_mqtt.rb.  Sure enough, it works without it!

So, for me the solution to get this working was to do the following:

change  first line of mac_airtag_to_mqtt.rb from `#!/Users/ndbroadbent/.rbenv/versions/3.1.2/bin/ruby` to `#!/Users/[[MyUserName]]/.rbenv/versions/3.1.2/bin/ruby`

and comment out `require 'pry-byebug'`

I hope this helps others get this working!

**Comment by martindinicolino** [comment]
i would really need an installation guide for newbies that are willing to learn 😅

if i understand it correctly i will need to install ruby and launchcontrol on my mac, then download the code from github, customise the .env file and in the end manually put the files in the correct folders, is that right?
what am i missing?
